### ISSUE TITLE
Typo in warning communicate on the bin2dip.php

### ISSUE THREAD

**Issue by kluszon** [Fifcok/count_all#2]
I observed the typo in warning communicate on the bin2dip.php when you input value out off range.

![image](https://user-images.githubusercontent.com/20355040/193032439-a23befcb-a635-48f8-8ca8-59e97248e36d.png)

**Comment by jakub-warchol** [comment]
I've observed this issue too. @Fifcok please fix that shit mistake in beautiful Polish speech!!!
