### ISSUE TITLE
Pomysł

### ISSUE THREAD

**Issue by xCarlossx** [Fifcok/count_all#6]
Według mnie ciekawym pomysłem byłoby przelicznik prędkości np. Węzły na mach, wysokością np. stopy na metry, odległością np. Mile na kilometry, i coś może  związanego z czasem np moc sprawdzić jaki w danym miejscu jest godziny różnicy od czasu zulu

**Comment by Fifcok** [comment]
- [x] **Prędkość**

km/h -> konts * 1.852
knots -> km/h * 0.539956803

- [x]  **Wysokość**

meter -> ft * 0.3048
ft -> meter * 3.28084

- [ ] **Czas Zulu**

https://timezonedb.com/download

[TimeZoneDB.csv.zip](https://github.com/Fifcok/count_all/files/9926392/TimeZoneDB.csv.zip)
[TimeZoneDB.sql.zip](https://github.com/Fifcok/count_all/files/9926406/TimeZoneDB.sql.zip)

America/Los_Angeles,US,PDT,16320823200,-25200,1

Wartość w 5 kolumnie (gmt_offset) podzielić przez 3600, aby otrzymać godziny
